name: Build and Push Docker Image

on:
  release:
    types: [created]

permissions: write-all

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm/v8,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/webui-privaxy-revived:latest
            ghcr.io/${{ github.repository_owner }}/webui-privaxy-revived:${{ github.event.release.tag_name }}
